spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    name: springit
  h2:
    console:
      enabled: true
  profiles:
    active:
      - dev
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS


#logging:
#  level:
##    root: ERROR
#    com.jin.springit: INFO

info:
  application:
    name: Springit
    description: Reddit clone using Spring Boot 2
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS











