spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    name: springit
  h2:
    console:
      enabled: true

#  spring.jpa.hibernate.ddl-auto=create
#  spring.datasource.url=jdbc:mysql://localhost:3306/springit?useSSL=false
#  spring.datasource.username=springit
#  spring.datasource.password=password

#  jpa:
#    hibernate:
#      ddl-auto: none
#  datasource:
#    url: jdbc:mysql://localhost:3308/springit?useSSL=false
#    username: root
#    password: password
#    initialization-mode: ALWAYS


  profiles:
    active:
      - dev
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS


logging:
  level:
    root: off
    com.jin.springit: INFO

info:
  application:
    name: Springit
    description: Reddit clone using Spring Boot 2
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS











